/**
 * Ticketline API
 * Documentation for the Ticketline API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum Category {
    Classical = 'Classical',
    Country = 'Country',
    Edm = 'EDM',
    Jazz = 'Jazz',
    Oldies = 'Oldies',
    Pop = 'Pop',
    Rap = 'Rap',
    RnB = 'RnB',
    Rock = 'Rock',
    Techno = 'Techno'
};

