/**
 * Ticketline API
 * Documentation for the Ticketline API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Seat } from './seat';
import { ProvisionalSector } from './provisionalSector';
import { SeatingPlanLayout } from './seatingPlanLayout';


export interface SeatingPlanWithoutId { 
    name: string;
    seatingPlanLayout?: SeatingPlanLayout;
    locationId: number;
    sectors: Array<ProvisionalSector>;
    seats: Array<Seat>;
}

