export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './artists.service';
import { ArtistsService } from './artists.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './seatingPlans.service';
import { SeatingPlansService } from './seatingPlans.service';
export * from './shows.service';
import { ShowsService } from './shows.service';
export * from './tickets.service';
import { TicketsService } from './tickets.service';
export * from './userManagement.service';
import { UserManagementService } from './userManagement.service';
export const APIS = [ArticlesService, ArtistsService, AuthService, EventsService, LocationsService, SeatingPlansService, ShowsService, TicketsService, UserManagementService];
